function [MSE,SMSE, MSLL] = evaluate2(x, y, xt, yt, mu_dGP, s2_dGP)
    MSE  = mean((mu_dGP - yt).^2);
    SMSE = MSE / var(yt);
    s2p   = 0.5*mean(log(2*pi*s2_dGP));
    s2    = 0.5*log(2*pi*std(y)^2);
    lossp = (yt-mu_dGP).^2;
    mup   = 0.5*mean(lossp./s2_dGP);
    dt    = size(xt,1);
    muv   = ones(dt,1)*mean(y);
    loss  = (yt-muv).^2;
    mu    = 0.5*mean(loss/(std(y)^2)); 
    MSLL  = s2p-s2+mup-mu;